# hostname (and path) to the root eg. https://appernetic.github.io/
baseurl = "/"

# Remark if you want to disable multilingual support.
DefaultContentLanguage = "en"

# If you want all of the languages to be put below their respective language code,
# enable DefaultContentLanguageInSubdir = true. Without enabling it english content
# will be in the root and other languages in their respective subfolder such as /sv/.
# See [Languages] settings at the end of this file.

# Use this languageCode if it's not a multilingual site and also remove all language blocks and menus in the language sections to disable multilingual support.
# language blocks.
# Language
#languageCode = "en"

# SES friendly url:s
canonifyurls = true

# Frontmatter format
# "yaml", "toml", "json"
metaDataFormat = "toml"

# Theme to use (located in /themes/THEMENAME/)
theme = "hugo-bootstrap-premium"
# Pagination
paginate = 10
paginatePath = "page"

# Enable Disqus integration
disqusShortname = "www-pawangaria-com"
enableRobotsTXT= true
[sitemap]
  changefreq = "weekly"
  priority = 0.9
  filename = "sitemap.xml"

[permalinks]
#post = "/:year/:month/:day/:filename/"
#code = "/:filename/"

[taxonomies]
tag = "tags"
topic = "topics"
categories = "categories"

[author]
name = "Pawan Garia"
email = "pawangaria@gmail.com"

#
# All parameters below here are optional and can be mixed and matched.
#

[params.theme]
name = "paper"

[params.popover]
# This is a highly configurable popover form.
enablepopover = false #enable or disable popover: true/false.
posturl = "https://zapier.com/hooks/catch/1227563/" # Your zapier post hook.
headerimage = "//placehold.it/1000x600"
expirecookie = 5 #show it again after number of days to visitors that has not subscribed.
cookiename = "mycookie1" #give the cookie a unique name variable (avoid spaces and strange characters).
signupheader = "Join Our Newsletter"
showmodaltimeout = 10000 #show popover modal after time interval in milliseconds.
mouseleave = true #show popover when mouse leaves window: true/false.
modalsize = "" #lg or sm. Empty is md. If phone is detected lg is used.
imagedescription = "Placeholder image for this popover modal optin form"
signuptext = "Signup today for free and be the first to get notified on new updates."
inputplaceholder = "Enter your email"
submitbutton = "Subscribe"
successmessage = "Thanks for your subscription!"
errormessage = "Submitting form failed!"
optin = true #opt-in: true/false

[params]
# menu for changing language. This changes languages with js and stores the choice with the help of JavaScript in a Cookie. Then the path is rewritten with pathnamereplace.js. The name of the md files needs to have the same name for each language abbreviation to work correctly. Example: showcase.en.md and showcase.sv.md. It only works if DefaultContentLanguageInSubdir = true
switchlang = false
# You can use markdown here.
BrandImage = "/img/pawangaria.png" #top header brand image.
brand = "PawanGaria.com" # brand image alt text.
topline = "Testing, Automation, Programming and Latest Technology Articles"
footline = "code with <i class='fa fa-heart'></i>"
title = "Testing, Automation, Programming and Latest Technology Articles" # Site title
description = "Resources for Java and Automation testing developers - Provides article about WebDriver, Automation Testing, Framework Design and Java."
keywords = "Selenium,WebDriver,ChromeDriver,Automation Testing,Java,TestNG,TestRail,Quality Assurance,HTTP,JSON,Automation testing tutorials"

customJS = []
customCSS = ["/css/style_custom.css"]

# Text for the top menu link, which goes to the root URL for the site.
# Default (if omitted) is "Home".
home = "home"

mailmunchid = "" # Mailmunch site id
sumomeid = "" # Sumome id
mathjax = "2.7.1" # cdnjs hosted version; empty string to disable mathjax

# Show a sidebar menu
showRightSidebar = true
# Select a syntax highlight.
# Check the static/css/highlight directory for options.
highlight = "default"

# Google Analytics.
googleAnalytics = "UA-110208829-1"
googleads = true
# Sidebar social links.
name = "Pawan garia"
website = "www.pawangaria.com"
email = "pawangaria@gmail.com"
facebook = "pawan.garia"
linkedin = "pawan-garia-a947a24a"

[blackfriday]
angledQuotes = true
fractions = false
hrefTargetBlank = false
latexDashes = true
plainIdAnchors = true
extensions = []
extensionmask = []

# Menus
# If you want active menu items highlighted for internal pages don't add them here, they need to be added in each files front matter.
# like this:
#[menu]
#     [menu.main]
#        name = "Showcase"
#        weight = 3
#        identifier = "showcase"
# i18n menus. A menu will be added for each language to the right in the top menu. This menu will switch to the selected language. Remember to add the corresponding language in pathnamereplace.js.
#[[Languages.sv.menu.switchlang]]
#  name = "English"
#  identifier = ""
#  weight = 4
#  url = "en"

[[menu.main]]
name = "Blog"
pre = ""
weight = 1
identifier = "post"
url = "/post/"

[[menu.main]]
name = "About"
weight = 3
identifier = "about"
url = "page/about/"

[[menu.main]]
    identifier = "category"
    name = "Categories"
    weight = 2
    hasChildren = true
    url = "categories/"

[[menu.main]]
        parent = "category"
        name = "Automation Testing"
        url = "categories/automation-testing/"
        weight = 1
[[menu.main]]
        parent = "category"
        name = "Selenium WebDriver"
        url = "categories/selenium-webdriver/"
        weight = 2
[[menu.main]]
        parent = "category"
        name = "Resources And Guides"
        url = "categories/resources-and-guides/"
        weight = 3
[[menu.main]]
        parent = "category"
        name = "Tutorials"
        url = "categories/tutorials/"
        weight = 4
